spring.application.name=config-service-api
server.error.include-stacktrace=never

spring.datasource.url=jdbc:postgresql://localhost:5432/config_service
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

