# Nome da aplicação Spring Boot
spring.application.name=config-service-api
server.error.include-stacktrace=never

# Configuração do banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/config_service
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update


# Configuração do Redis (cache)
spring.data.reds.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis